### ISSUE TITLE
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by yuxin321** [cran/amt#1]
Hi,  I try to run the code of transforming geographical coordinates in a article named "Animal movement tools (amt): R package for managing tracking data and conducting habitat selection analyses". 
And then there is an error : Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : non-numeric argument to binary operator. 

I ran it completely according to the code in the article and the sample data downloaded from the movebank.

I would appreciate it if you can tell me how to solve it.

Thanks for your generous help!

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by yuxin321** [comment]
Thank you so much. My apologies for inconvenience！
